apiVersion: v1
kind: Pod
metadata:
  labels:
    app: workload
  name: workload
spec:
  containers:
  - image: sckmkny/workload:0.2.0
    name: workload
    ports:
    - name: grpc
      containerPort: 50051
    livenessProbe:
      exec:
        command:
        - grpcurl
        - -plaintext
        - localhost:50051
        - ping.Pinger/Ping
    readinessProbe:
      exec:
        command:
        - grpc_health_probe
        - -addr=:50051

