apiVersion: v1
kind: Service
metadata:
  labels:
    app: workload
  name: workload
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: grpc
  selector:
    app: workload

