apiVersion: v1
kind: Pod
metadata:
  labels:
    app: workload
  name: workload
spec:
  containers:
  - image: sckmkny/workload:0.1.0
    name: workload
    ports:
    - name: grpc
      containerPort: 50051
    readinessProbe:
      exec:
        command: ["grpc_health_probe", "-addr=:50051"]

